#!/usr/bin/env python3
"""
Drone Remote ID SQLite Encounter Query & Export Utility
Allows searching, table formatting, detailed flight inspection, and GeoJSON/CSV export
from the persistent SQLite database generated by combined_rid_listener.py.

Usage examples:
  python3 query_rid_db.py list
  python3 query_rid_db.py list --mac 60:60:1F:AA:BB:CC --since "2026-08-20"
  python3 query_rid_db.py show ENC-20260825-141510-AABBCC
  python3 query_rid_db.py export-geojson ENC-20260825-141510-AABBCC -o flight_track.geojson
  python3 query_rid_db.py export-csv ENC-20260825-141510-AABBCC -o flight_track.csv
  python3 query_rid_db.py stats
"""

import argparse
import csv
import json
import os
import sqlite3
import sys
import time
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Tuple

# ANSI Formatting
C_RESET = "\033[0m"
C_BOLD = "\033[1m"
C_RED = "\033[91m"
C_GREEN = "\033[92m"
C_YELLOW = "\033[93m"
C_BLUE = "\033[94m"
C_MAGENTA = "\033[95m"
C_CYAN = "\033[96m"
C_WHITE = "\033[97m"
C_GRAY = "\033[90m"


def format_duration(seconds: float) -> str:
    """Format duration in seconds into human-readable string (e.g. 3m 42s)."""
    secs = int(round(seconds))
    if secs < 60:
        return f"{secs}s"
    mins = secs // 60
    rem_secs = secs % 60
    if mins < 60:
        return f"{mins}m {rem_secs:02d}s"
    hours = mins // 60
    rem_mins = mins % 60
    return f"{hours}h {rem_mins:02d}m"


def get_db_connection(db_path: str) -> sqlite3.Connection:
    if not os.path.exists(db_path):
        print(f"{C_RED}[-] Error: Database file '{db_path}' does not exist.{C_RESET}")
        sys.exit(1)
    conn = sqlite3.connect(db_path, timeout=10.0)
    conn.row_factory = sqlite3.Row
    return conn


def reconcile_stale_encounters(conn: sqlite3.Connection, timeout_s: float = 300.0):
    """Marks any encounters that have exceeded the silence timeout as is_active = 0 in SQLite."""
    try:
        now = time.time()
        conn.execute("UPDATE encounters SET is_active = 0 WHERE is_active = 1 AND (? - last_seen) > ?;",
                     (now, timeout_s))
        conn.commit()
    except Exception:
        pass


# ============================================================================
# Command: list
# ============================================================================

def cmd_list(args):
    conn = get_db_connection(args.db)
    timeout_s = getattr(args, "timeout_s", 300.0)
    reconcile_stale_encounters(conn, timeout_s)

    query = "SELECT * FROM encounters WHERE 1=1"
    params = []

    if args.mac:
        query += " AND mac LIKE ?"
        params.append(f"%{args.mac}%")
    if args.serial:
        query += " AND serial_number LIKE ?"
        params.append(f"%{args.serial}%")
    if args.active_only:
        query += " AND is_active = 1"
    if args.since:
        try:
            dt = datetime.fromisoformat(args.since).timestamp()
            query += " AND first_seen >= ?"
            params.append(dt)
        except Exception:
            print(f"{C_RED}[-] Error: Invalid date format for --since (use ISO format, e.g. 2026-08-25).{C_RESET}")
            sys.exit(1)

    query += " ORDER BY first_seen DESC"
    if args.limit:
        query += f" LIMIT {args.limit}"

    rows = conn.execute(query, params).fetchall()

    if not rows:
        print(f"{C_YELLOW}[*] No flight encounters found matching criteria in {args.db}.{C_RESET}")
        return

    print(f"\n{C_BOLD}{C_CYAN}🚁 RECORDED DRONE FLIGHT ENCOUNTERS ({len(rows)} found){C_RESET}")
    print(f"{C_GRAY}Database: {args.db}{C_RESET}\n")

    # Header
    hdr = f"{'ENCOUNTER ID':<26} {'START TIME (UTC)':<19} {'DURATION':<10} {'PKTS':<6} {'MAC':<18} {'SERIAL / UAS ID':<22} {'TRANSPORTS':<14} {'MAX ALT':<9} {'STATUS':<8}"
    print(f"{C_BOLD}{hdr}{C_RESET}")
    print(f"{C_GRAY}{'-'*len(hdr)}{C_RESET}")

    now = time.time()
    for r in rows:
        enc_id = r["encounter_id"]
        start_str = r["first_seen_iso"][:19].replace("T", " ")
        dur_str = format_duration(r["duration_s"])
        pkts = r["packet_count"]
        mac = r["mac"]
        serial = r["serial_number"] or f"{C_GRAY}<None>{C_RESET}"
        transports = r["transports"]
        max_alt = f"{r['max_alt_m']:.1f}m" if r["max_alt_m"] is not None else f"{C_GRAY}-{C_RESET}"
        is_active = bool(r["is_active"] and (now - r["last_seen"] <= timeout_s))
        status = f"{C_GREEN}ACTIVE{C_RESET}" if is_active else f"{C_GRAY}CLOSED{C_RESET}"

        print(f"{C_WHITE}{enc_id:<26}{C_RESET} {start_str:<19} {dur_str:<10} {pkts:<6} {mac:<18} {serial:<22} {transports:<14} {max_alt:<9} {status:<8}")

    print(f"{C_GRAY}{'-'*len(hdr)}{C_RESET}\n")


# ============================================================================
# Command: show
# ============================================================================

def cmd_show(args):
    conn = get_db_connection(args.db)
    timeout_s = getattr(args, "timeout_s", 300.0)
    reconcile_stale_encounters(conn, timeout_s)

    query_str = """
        SELECT * FROM encounters 
        WHERE encounter_id = ? OR encounter_id LIKE ? 
           OR serial_number = ? OR serial_number LIKE ?
           OR mac = ? OR mac LIKE ?
        ORDER BY first_seen DESC LIMIT 1
    """
    row = conn.execute(query_str, (
        args.encounter_id, f"%{args.encounter_id}%",
        args.encounter_id, f"%{args.encounter_id}%",
        args.encounter_id, f"%{args.encounter_id}%"
    )).fetchone()

    if not row:
        print(f"{C_RED}[-] Error: Encounter '{args.encounter_id}' not found in {args.db}.{C_RESET}")
        sys.exit(1)

    print(f"\n{C_BOLD}{C_GREEN}{'='*65}{C_RESET}")
    print(f"{C_BOLD}🚁 FLIGHT ENCOUNTER DETAILS: {row['encounter_id']}{C_RESET}")
    print(f"{C_BOLD}{'='*65}{C_RESET}")

    is_active = bool(row["is_active"] and (time.time() - row["last_seen"] <= timeout_s))
    status_str = f"{C_GREEN}ACTIVE (In Progress){C_RESET}" if is_active else f"{C_GRAY}CLOSED (Completed){C_RESET}"
    print(f"  • {C_BOLD}Status           :{C_RESET} {status_str}")
    print(f"  • {C_BOLD}Transmitter MAC  :{C_RESET} {row['mac']}")
    print(f"  • {C_BOLD}UAS Serial Number:{C_RESET} {row['serial_number'] or 'Not Broadcasted'}")
    print(f"  • {C_BOLD}Operator ID      :{C_RESET} {row['operator_id'] or 'Not Broadcasted'}")
    print(f"  • {C_BOLD}Self-ID Desc     :{C_RESET} \"{row['self_id_desc'] or ''}\"")
    print(f"  • {C_BOLD}First Detected   :{C_RESET} {row['first_seen_iso']}")
    print(f"  • {C_BOLD}Last Detected    :{C_RESET} {row['last_seen_iso']}")
    print(f"  • {C_BOLD}Duration         :{C_RESET} {format_duration(row['duration_s'])} ({row['duration_s']:.1f} seconds)")
    print(f"  • {C_BOLD}Total Packets    :{C_RESET} {row['packet_count']}")
    print(f"  • {C_BOLD}Transports Used  :{C_RESET} {row['transports']}")
    print(f"  • {C_BOLD}Channels Active  :{C_RESET} {row['channels']}")

    # Signal & Telemetry stats
    rssi_min = f"{row['min_rssi_dbm']} dBm" if row['min_rssi_dbm'] is not None else "N/A"
    rssi_max = f"{row['max_rssi_dbm']} dBm" if row['max_rssi_dbm'] is not None else "N/A"
    rssi_avg = f"{row['avg_rssi_dbm']} dBm" if row['avg_rssi_dbm'] is not None else "N/A"
    print(f"  • {C_BOLD}Signal RSSI      :{C_RESET} Min: {rssi_min} | Max: {rssi_max} | Avg: {rssi_avg}")

    alt_min = f"{row['min_alt_m']:.1f} m" if row['min_alt_m'] is not None else "N/A"
    alt_max = f"{row['max_alt_m']:.1f} m" if row['max_alt_m'] is not None else "N/A"
    print(f"  • {C_BOLD}Altitude Range   :{C_RESET} Min: {alt_min} | Max: {alt_max}")

    max_spd = f"{row['max_speed_mps']:.1f} m/s ({row['max_speed_mps']*3.6:.1f} km/h)" if row['max_speed_mps'] is not None else "N/A"
    print(f"  • {C_BOLD}Max Ground Speed :{C_RESET} {max_spd}")

    if row['pilot_lat'] is not None and row['pilot_lon'] is not None:
        p_alt = f"{row['pilot_alt_m']:.1f}m" if row['pilot_alt_m'] is not None else "N/A"
        print(f"  • {C_BOLD}Pilot / Home Pos :{C_RESET} Lat: {row['pilot_lat']:.6f}, Lon: {row['pilot_lon']:.6f}, Alt: {p_alt}")

    # Trajectory preview
    traj = json.loads(row["trajectory_json"]) if row["trajectory_json"] else []
    print(f"\n{C_BOLD}📍 Trajectory Points Captured: {len(traj)}{C_RESET}")
    if traj:
        print(f"  - First Point: Lat={traj[0][0]:.6f}, Lon={traj[0][1]:.6f}, Alt={traj[0][2]}m, Speed={traj[0][3]}m/s")
        if len(traj) > 1:
            print(f"  - Last Point : Lat={traj[-1][0]:.6f}, Lon={traj[-1][1]:.6f}, Alt={traj[-1][2]}m, Speed={traj[-1][3]}m/s")
    print(f"{C_BOLD}{'='*65}{C_RESET}\n")


# ============================================================================
# Command: export-geojson
# ============================================================================

def cmd_export_geojson(args):
    conn = get_db_connection(args.db)
    query_str = """
        SELECT * FROM encounters 
        WHERE encounter_id = ? OR encounter_id LIKE ? 
           OR serial_number = ? OR serial_number LIKE ?
           OR mac = ? OR mac LIKE ?
        ORDER BY first_seen DESC LIMIT 1
    """
    row = conn.execute(query_str, (
        args.encounter_id, f"%{args.encounter_id}%",
        args.encounter_id, f"%{args.encounter_id}%",
        args.encounter_id, f"%{args.encounter_id}%"
    )).fetchone()

    if not row:
        print(f"{C_RED}[-] Error: Encounter '{args.encounter_id}' not found in {args.db}.{C_RESET}")
        sys.exit(1)

    traj = json.loads(row["trajectory_json"]) if row["trajectory_json"] else []
    if not traj:
        print(f"{C_YELLOW}[!] Warning: Encounter '{row['encounter_id']}' contains no geographic trajectory points.{C_RESET}")
        return

    features = []

    # 1. Flight LineString Feature (GeoJSON coordinates are [lon, lat, alt])
    line_coords = [[pt[1], pt[0], pt[2] if pt[2] is not None else 0.0] for pt in traj]
    flight_feature = {
        "type": "Feature",
        "properties": {
            "encounter_id": row["encounter_id"],
            "mac": row["mac"],
            "serial_number": row["serial_number"],
            "operator_id": row["operator_id"],
            "first_seen": row["first_seen_iso"],
            "last_seen": row["last_seen_iso"],
            "duration_s": row["duration_s"],
            "packet_count": row["packet_count"],
            "max_speed_mps": row["max_speed_mps"],
            "max_alt_m": row["max_alt_m"],
            "stroke": "#00ff88",
            "stroke-width": 4
        },
        "geometry": {
            "type": "LineString",
            "coordinates": line_coords
        }
    }
    features.append(flight_feature)

    # 2. Start and End Position Points
    start_pt = {
        "type": "Feature",
        "properties": {
            "name": f"Flight Start: {row['encounter_id']}",
            "timestamp": row["first_seen_iso"],
            "marker-color": "#0088ff",
            "marker-symbol": "airport"
        },
        "geometry": {
            "type": "Point",
            "coordinates": [traj[0][1], traj[0][0], traj[0][2] if traj[0][2] is not None else 0.0]
        }
    }
    features.append(start_pt)

    if len(traj) > 1:
        end_pt = {
            "type": "Feature",
            "properties": {
                "name": f"Flight End: {row['encounter_id']}",
                "timestamp": row["last_seen_iso"],
                "marker-color": "#ff3333",
                "marker-symbol": "land"
            },
            "geometry": {
                "type": "Point",
                "coordinates": [traj[-1][1], traj[-1][0], traj[-1][2] if traj[-1][2] is not None else 0.0]
            }
        }
        features.append(end_pt)

    # 3. Pilot / Home Position Point if available
    if row["pilot_lat"] is not None and row["pilot_lon"] is not None:
        pilot_pt = {
            "type": "Feature",
            "properties": {
                "name": f"Pilot / Operator Location ({row['operator_id'] or 'Unknown'})",
                "marker-color": "#ffaa00",
                "marker-symbol": "heliport"
            },
            "geometry": {
                "type": "Point",
                "coordinates": [row["pilot_lon"], row["pilot_lat"], row["pilot_alt_m"] if row["pilot_alt_m"] is not None else 0.0]
            }
        }
        features.append(pilot_pt)

    geojson_doc = {
        "type": "FeatureCollection",
        "features": features
    }

    out_path = args.output or f"{row['encounter_id']}.geojson"
    with open(out_path, "w") as f:
        json.dump(geojson_doc, f, indent=2)

    print(f"{C_GREEN}[+] Successfully exported GeoJSON trajectory ({len(traj)} points) to {out_path}{C_RESET}")
    print(f"{C_GRAY}    Tip: Drag and drop {out_path} into https://geojson.io to visualize the flight track!{C_RESET}")


# ============================================================================
def sanitize_csv_cell(val: Any) -> Any:
    """
    Neutralize spreadsheet formula macro injection (ANDR-01, RDBP-03).
    Prepends a single quote if a text value starts with =, +, -, @, \\t, or \\r.
    """
    if isinstance(val, str) and val and val[0] in ('=', '+', '-', '@', '\t', '\r'):
        return f"'{val}"
    return val


def cmd_export_csv(args):
    conn = get_db_connection(args.db)
    query_str = """
        SELECT * FROM encounters 
        WHERE encounter_id = ? OR encounter_id LIKE ? 
           OR serial_number = ? OR serial_number LIKE ?
           OR mac = ? OR mac LIKE ?
        ORDER BY first_seen DESC LIMIT 1
    """
    row = conn.execute(query_str, (
        args.encounter_id, f"%{args.encounter_id}%",
        args.encounter_id, f"%{args.encounter_id}%",
        args.encounter_id, f"%{args.encounter_id}%"
    )).fetchone()

    if not row:
        print(f"{C_RED}[-] Error: Encounter '{args.encounter_id}' not found in {args.db}.{C_RESET}")
        sys.exit(1)

    traj = json.loads(row["trajectory_json"]) if row["trajectory_json"] else []
    if not traj:
        print(f"{C_YELLOW}[!] Warning: Encounter '{row['encounter_id']}' contains no trajectory points.{C_RESET}")
        return

    out_path = args.output or f"{row['encounter_id']}.csv"
    with open(out_path, "w", newline="") as f:
        writer = csv.writer(f, quoting=csv.QUOTE_MINIMAL)
        writer.writerow(["index", "timestamp_epoch", "latitude", "longitude", "altitude_m", "speed_mps", "heading_deg"])
        for idx, pt in enumerate(traj):
            # pt: [lat, lon, alt, speed, heading, ts]
            writer.writerow([idx, sanitize_csv_cell(pt[5]), pt[0], pt[1], pt[2], pt[3], pt[4]])

    print(f"{C_GREEN}[+] Successfully exported CSV trajectory ({len(traj)} points) to {out_path}{C_RESET}")


# ============================================================================
# Command: stats
# ============================================================================

def cmd_stats(args):
    conn = get_db_connection(args.db)
    timeout_s = getattr(args, "timeout_s", 300.0)
    reconcile_stale_encounters(conn, timeout_s)

    total_enc = conn.execute("SELECT COUNT(*) FROM encounters").fetchone()[0]
    active_enc = conn.execute("SELECT COUNT(*) FROM encounters WHERE is_active = 1").fetchone()[0]
    total_pkts = conn.execute("SELECT SUM(packet_count) FROM encounters").fetchone()[0] or 0
    unique_macs = conn.execute("SELECT COUNT(DISTINCT mac) FROM encounters").fetchone()[0]
    unique_serials = conn.execute("SELECT COUNT(DISTINCT serial_number) FROM encounters WHERE serial_number IS NOT NULL").fetchone()[0]
    unique_ops = conn.execute("SELECT COUNT(DISTINCT operator_id) FROM encounters WHERE operator_id IS NOT NULL").fetchone()[0]

    min_time_iso = conn.execute("SELECT MIN(first_seen_iso) FROM encounters").fetchone()[0]
    max_time_iso = conn.execute("SELECT MAX(last_seen_iso) FROM encounters").fetchone()[0]

    print(f"\n{C_BOLD}{C_CYAN}{'='*60}{C_RESET}")
    print(f"{C_BOLD}📊 AIRSPACE MONITORING DATABASE METRICS{C_RESET}")
    print(f"{C_GRAY}Database: {args.db}{C_RESET}")
    print(f"{C_BOLD}{'='*60}{C_RESET}")
    print(f"  • Total Flight Encounters : {C_BOLD}{total_enc}{C_RESET} ({active_enc} active, {total_enc - active_enc} closed)")
    print(f"  • Total RID Packets Logged: {C_BOLD}{total_pkts:,}{C_RESET}")
    print(f"  • Unique Drones (MACs)    : {C_BOLD}{unique_macs}{C_RESET}")
    print(f"  • Unique UAS Serial IDs   : {C_BOLD}{unique_serials}{C_RESET}")
    print(f"  • Unique Operator IDs     : {C_BOLD}{unique_ops}{C_RESET}")
    if min_time_iso and max_time_iso:
        print(f"  • First Observation       : {min_time_iso}")
        print(f"  • Latest Observation      : {max_time_iso}")
    print(f"{C_BOLD}{'='*60}{C_RESET}\n")


# ============================================================================
# Main CLI Router
# ============================================================================

def main():
    parser = argparse.ArgumentParser(
        description="Drone Remote ID SQLite Database Search, Inspection & Export Utility",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    parser.add_argument("--db", default="rid_detections.db", help="Path to SQLite database file")
    parser.add_argument("--timeout-s", "--timeout", dest="timeout_s", type=float, default=300.0,
                        help="Flight encounter silence timeout in seconds (default: 300s)")

    subparsers = parser.add_subparsers(dest="command", required=True, help="Command to execute")

    # Command: list
    p_list = subparsers.add_parser("list", help="List recorded drone flight encounters")
    p_list.add_argument("--mac", help="Filter by transmitter MAC address")
    p_list.add_argument("--serial", help="Filter by UAS Serial Number")
    p_list.add_argument("--since", help="Filter encounters starting after ISO date (e.g. 2026-08-25)")
    p_list.add_argument("--active-only", action="store_true", help="Only show currently active encounters")
    p_list.add_argument("--limit", type=int, default=50, help="Maximum encounters to show")

    # Command: show
    p_show = subparsers.add_parser("show", help="Show detailed breakdown of a flight encounter")
    p_show.add_argument("encounter_id", help="Encounter ID (e.g. ENC-20260825-141510-AABBCC)")

    # Command: export-geojson
    p_geojson = subparsers.add_parser("export-geojson", help="Export flight trajectory to RFC 7946 GeoJSON format")
    p_geojson.add_argument("encounter_id", help="Encounter ID to export")
    p_geojson.add_argument("-o", "--output", help="Output .geojson file path")

    # Command: export-csv
    p_csv = subparsers.add_parser("export-csv", help="Export flight trajectory points to CSV")
    p_csv.add_argument("encounter_id", help="Encounter ID to export")
    p_csv.add_argument("-o", "--output", help="Output .csv file path")

    # Command: stats
    subparsers.add_parser("stats", help="Show global database statistics and summary")

    args = parser.parse_args()

    if args.command == "list":
        cmd_list(args)
    elif args.command == "show":
        cmd_show(args)
    elif args.command == "export-geojson":
        cmd_export_geojson(args)
    elif args.command == "export-csv":
        cmd_export_csv(args)
    elif args.command == "stats":
        cmd_stats(args)


if __name__ == "__main__":
    main()
